apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6380
    targetPort: 6380
    protocol: TCP
    name: http
  selector:
    app: redis
